substitutions:
  name: jkbms
  bms0: front_cabinet
  bms1: rear_cabinet
  bms2: garage
  device_description: "Monitor and control a JK-BMS via bluetooth"
  external_components_source: github://syssi/esphome-jk-bms@main
  bms0_mac_address: FILL THIS IN
  bms1_mac_address: FILL THIS IN
  bms2_mac_address: FILL THIS IN
  # Please use "JK02_24S" if you own a old JK-BMS < hardware version 11.0 (hardware version >= 6.0 and < 11.0)
  # Please use "JK02_32S" if you own a new JK-BMS >= hardware version 11.0 (f.e. JK-B2A8S20P hw 11.XW, sw 11.26)
  # Please use "JK04" if you have some old JK-BMS <= hardware version 3.0 (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  bms0_protocol_version: JK02_32S
  bms1_protocol_version: JK02_32S
  bms2_protocol_version: JK02_32S
  friendly_name: jkbms monitor

esphome:
  name: ${name}
  comment: ${device_description}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.0.0

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  # Set up a wifi access point
  ap: {}

ota:
  platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - switch.turn_off: ble_client_switch1
      - switch.turn_off: ble_client_switch2
      - logger.log: "BLE connection suspended for OTA update"

logger:
  level: DEBUG

api:

ble_client:
  - mac_address: ${bms0_mac_address}
    id: client0
  - mac_address: ${bms1_mac_address}
    id: client1
  - mac_address: ${bms2_mac_address}
    id: client2

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${bms0_protocol_version}
    throttle: 5s
    id: bms0
  - ble_client_id: client1
    protocol_version: ${bms1_protocol_version}
    throttle: 5s
    id: bms1
  - ble_client_id: client2
    protocol_version: ${bms2_protocol_version}
    throttle: 5s
    id: bms2

binary_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balancing:
      name: "${bms0} balancing"
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"
    heating:
      name: "${bms0} heating"
    online_status:
      name: "${bms0} online status"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    balancing:
      name: "${bms1} balancing"
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"
    heating:
      name: "${bms1} heating"
    online_status:
      name: "${bms1} online status"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms2
    balancing:
      name: "${bms2} balancing"
    charging:
      name: "${bms2} charging"
    discharging:
      name: "${bms2} discharging"
    heating:
      name: "${bms2} heating"
    online_status:
      name: "${bms2} online status"

button:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    retrieve_settings:
      name: "${bms0} retrieve settings"
    retrieve_device_info:
      name: "${bms0} retrieve device info"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    retrieve_settings:
      name: "${bms1} retrieve settings"
    retrieve_device_info:
      name: "${bms1} retrieve device info"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms2
    retrieve_settings:
      name: "${bms2} retrieve settings"
    retrieve_device_info:
      name: "${bms2} retrieve device info"

number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "${bms0} balance trigger voltage"
    cell_count:
      name: "${bms0} cell count"
    total_battery_capacity:
      name: "${bms0} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${bms0} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${bms0} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${bms0} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${bms0} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${bms0} balance starting voltage"
    voltage_calibration:
      name: "${bms0} voltage calibration"
    current_calibration:
      name: "${bms0} current calibration"
    power_off_voltage:
      name: "${bms0} power off voltage"
    max_balance_current:
      name: "${bms0} max balance current"
    max_charge_current:
      name: "${bms0} max charge current"
    max_discharge_current:
      name: "${bms0} max discharge current"
    
  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    balance_trigger_voltage:
      name: "${bms1} balance trigger voltage"
    cell_count:
      name: "${bms1} cell count"
    total_battery_capacity:
      name: "${bms1} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${bms1} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${bms1} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${bms1} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${bms1} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${bms1} balance starting voltage"
    voltage_calibration:
      name: "${bms1} voltage calibration"
    current_calibration:
      name: "${bms1} current calibration"
    power_off_voltage:
      name: "${bms1} power off voltage"
    max_balance_current:
      name: "${bms1} max balance current"
    max_charge_current:
      name: "${bms1} max charge current"
    max_discharge_current:
      name: "${bms1} max discharge current"
  
  - platform: jk_bms_ble
    jk_bms_ble_id: bms2
    balance_trigger_voltage:
      name: "${bms2} balance trigger voltage"
    cell_count:
      name: "${bms2} cell count"
    total_battery_capacity:
      name: "${bms2} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${bms2} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${bms2} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${bms2} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${bms2} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${bms2} balance starting voltage"
    voltage_calibration:
      name: "${bms2} voltage calibration"
    current_calibration:
      name: "${bms2} current calibration"
    power_off_voltage:
      name: "${bms2} power off voltage"
    max_balance_current:
      name: "${bms2} max balance current"
    max_charge_current:
      name: "${bms2} max charge current"
    max_discharge_current:
      name: "${bms2} max discharge current"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "${bms0} min cell voltage"
    max_cell_voltage:
      name: "${bms0} max cell voltage"
    min_voltage_cell:
      name: "${bms0} min voltage cell"
    max_voltage_cell:
      name: "${bms0} max voltage cell"
    delta_cell_voltage:
      name: "${bms0} delta cell voltage"
    average_cell_voltage:
      name: "${bms0} average cell voltage"
    cell_voltage_1:
      name: "${bms0} cell voltage 1"
    cell_voltage_2:
      name: "${bms0} cell voltage 2"
    cell_voltage_3:
      name: "${bms0} cell voltage 3"
    cell_voltage_4:
      name: "${bms0} cell voltage 4"
    cell_voltage_5:
      name: "${bms0} cell voltage 5"
    cell_voltage_6:
      name: "${bms0} cell voltage 6"
    cell_voltage_7:
      name: "${bms0} cell voltage 7"
    cell_voltage_8:
      name: "${bms0} cell voltage 8"
    cell_resistance_1:
      name: "${bms0} cell resistance 1"
    cell_resistance_2:
      name: "${bms0} cell resistance 2"
    cell_resistance_3:
      name: "${bms0} cell resistance 3"
    cell_resistance_4:
      name: "${bms0} cell resistance 4"
    cell_resistance_5:
      name: "${bms0} cell resistance 5"
    cell_resistance_6:
      name: "${bms0} cell resistance 6"
    cell_resistance_7:
      name: "${bms0} cell resistance 7"
    cell_resistance_8:
      name: "${bms0} cell resistance 8"
    total_voltage:
      name: "${bms0} total voltage"
    current:
      name: "${bms0} current"
    heating_current:
      name: "${bms0} heating current"
    power:
      name: "${bms0} power"
    charging_power:
      name: "${bms0} charging power"
    discharging_power:
      name: "${bms0} discharging power"
    temperature_sensor_1:
      name: "${bms0} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms0} temperature sensor 2"
    power_tube_temperature:
      name: "${bms0} power tube temperature"
    state_of_charge:
      name: "${bms0} state of charge"
    capacity_remaining:
      name: "${bms0} capacity remaining"
    total_battery_capacity_setting:
      name: "${bms0} total battery capacity setting"
    charging_cycles:
      name: "${bms0} charging cycles"
    total_charging_cycle_capacity:
      name: "${bms0} total charging cycle capacity"
    total_runtime:
      name: "${bms0} total runtime"
    balancing_current:
      name: "${bms0} balancing current"
    errors_bitmask:
      name: "${bms0} errors bitmask"
  
  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    min_cell_voltage:
      name: "${bms1} min cell voltage"
    max_cell_voltage:
      name: "${bms1} max cell voltage"
    min_voltage_cell:
      name: "${bms1} min voltage cell"
    max_voltage_cell:
      name: "${bms1} max voltage cell"
    delta_cell_voltage:
      name: "${bms1} delta cell voltage"
    average_cell_voltage:
      name: "${bms1} average cell voltage"
    cell_voltage_1:
      name: "${bms1} cell voltage 1"
    cell_voltage_2:
      name: "${bms1} cell voltage 2"
    cell_voltage_3:
      name: "${bms1} cell voltage 3"
    cell_voltage_4:
      name: "${bms1} cell voltage 4"
    cell_voltage_5:
      name: "${bms1} cell voltage 5"
    cell_voltage_6:
      name: "${bms1} cell voltage 6"
    cell_voltage_7:
      name: "${bms1} cell voltage 7"
    cell_voltage_8:
      name: "${bms1} cell voltage 8"
    cell_resistance_1:
      name: "${bms1} cell resistance 1"
    cell_resistance_2:
      name: "${bms1} cell resistance 2"
    cell_resistance_3:
      name: "${bms1} cell resistance 3"
    cell_resistance_4:
      name: "${bms1} cell resistance 4"
    cell_resistance_5:
      name: "${bms1} cell resistance 5"
    cell_resistance_6:
      name: "${bms1} cell resistance 6"
    cell_resistance_7:
      name: "${bms1} cell resistance 7"
    cell_resistance_8:
      name: "${bms1} cell resistance 8"
    total_voltage:
      name: "${bms1} total voltage"
    current:
      name: "${bms1} current"
    heating_current:
      name: "${bms1} heating current"
    power:
      name: "${bms1} power"
    charging_power:
      name: "${bms1} charging power"
    discharging_power:
      name: "${bms1} discharging power"
    temperature_sensor_1:
      name: "${bms1} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms1} temperature sensor 2"
    power_tube_temperature:
      name: "${bms1} power tube temperature"
    state_of_charge:
      name: "${bms1} state of charge"
    capacity_remaining:
      name: "${bms1} capacity remaining"
    total_battery_capacity_setting:
      name: "${bms1} total battery capacity setting"
    charging_cycles:
      name: "${bms1} charging cycles"
    total_charging_cycle_capacity:
      name: "${bms1} total charging cycle capacity"
    total_runtime:
      name: "${bms1} total runtime"
    balancing_current:
      name: "${bms1} balancing current"
    errors_bitmask:
      name: "${bms1} errors bitmask"
  
  - platform: jk_bms_ble
    jk_bms_ble_id: bms2
    min_cell_voltage:
      name: "${bms2} min cell voltage"
    max_cell_voltage:
      name: "${bms2} max cell voltage"
    min_voltage_cell:
      name: "${bms2} min voltage cell"
    max_voltage_cell:
      name: "${bms2} max voltage cell"
    delta_cell_voltage:
      name: "${bms2} delta cell voltage"
    average_cell_voltage:
      name: "${bms2} average cell voltage"
    cell_voltage_1:
      name: "${bms2} cell voltage 1"
    cell_voltage_2:
      name: "${bms2} cell voltage 2"
    cell_voltage_3:
      name: "${bms2} cell voltage 3"
    cell_voltage_4:
      name: "${bms2} cell voltage 4"
    cell_voltage_5:
      name: "${bms2} cell voltage 5"
    cell_voltage_6:
      name: "${bms2} cell voltage 6"
    cell_voltage_7:
      name: "${bms2} cell voltage 7"
    cell_voltage_8:
      name: "${bms2} cell voltage 8"
    cell_resistance_1:
      name: "${bms2} cell resistance 1"
    cell_resistance_2:
      name: "${bms2} cell resistance 2"
    cell_resistance_3:
      name: "${bms2} cell resistance 3"
    cell_resistance_4:
      name: "${bms2} cell resistance 4"
    cell_resistance_5:
      name: "${bms2} cell resistance 5"
    cell_resistance_6:
      name: "${bms2} cell resistance 6"
    cell_resistance_7:
      name: "${bms2} cell resistance 7"
    cell_resistance_8:
      name: "${bms2} cell resistance 8"
    total_voltage:
      name: "${bms2} total voltage"
    current:
      name: "${bms2} current"
    heating_current:
      name: "${bms2} heating current"
    power:
      name: "${bms2} power"
    charging_power:
      name: "${bms2} charging power"
    discharging_power:
      name: "${bms2} discharging power"
    temperature_sensor_1:
      name: "${bms2} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms2} temperature sensor 2"
    power_tube_temperature:
      name: "${bms2} power tube temperature"
    state_of_charge:
      name: "${bms2} state of charge"
    capacity_remaining:
      name: "${bms2} capacity remaining"
    total_battery_capacity_setting:
      name: "${bms2} total battery capacity setting"
    charging_cycles:
      name: "${bms2} charging cycles"
    total_charging_cycle_capacity:
      name: "${bms2} total charging cycle capacity"
    total_runtime:
      name: "${bms2} total runtime"
    balancing_current:
      name: "${bms2} balancing current"
    errors_bitmask:
      name: "${bms2} errors bitmask"


switch:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"
    balancer:
      name: "${bms0} balancer"

  - platform: ble_client
    ble_client_id: client0
    id: ble_client_switch0
    name: "${bms0} enable bluetooth connection"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"
    balancer:
      name: "${bms1} balancer"

  - platform: ble_client
    ble_client_id: client1
    id: ble_client_switch1
    name: "${bms1} enable bluetooth connection"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms2
    charging:
      name: "${bms2} charging"
    discharging:
      name: "${bms2} discharging"
    balancer:
      name: "${bms2} balancer"

  - platform: ble_client
    ble_client_id: client2
    id: ble_client_switch2
    name: "${bms2} enable bluetooth connection"

text_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    errors:
      name: "${bms0} errors"
    total_runtime_formatted:
      name: "${bms0} total runtime formatted"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    errors:
      name: "${bms1} errors"
    total_runtime_formatted:
      name: "${bms1} total runtime formatted"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms2
    errors:
      name: "${bms2} errors"
    total_runtime_formatted:
      name: "${bms2} total runtime formatted"
